# Dockerfile for running tests

FROM node:20-alpine

WORKDIR /usr/src/app

# Install Dependencies
COPY package*.json ./
RUN npm install

# Copy app source code
COPY . .

# Set NODE_ENV to test for Babel config
ENV NODE_ENV=test

# Run tests
CMD ["npm", "test"]

